repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
  - name: kiali
    url: https://kiali.org/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts

releases:
  # - name: istio-base
  #   namespace: istio-system
  #   createNamespace: true
  #   chart: istio/base
  #   version: 1.20.0
  #   wait: true
  #   hooks:
  #     - events: ["presync"]
  #       showlogs: true
  #       command: sh
  #       args:
  #         - "-c"
  #         - |
  #           kubectl delete validatingwebhookconfiguration istiod-default-validator 2>/dev/null || true
    
  # - name: istiod
  #   namespace: istio-system
  #   chart: istio/istiod
  #   version: 1.20.0
  #   needs:
  #     - istio-system/istio-base
  #   wait: true
  #   values:
  #     - istio/istiod-values.yaml

  # - name: istio-ingress
  #   namespace: istio-system
  #   chart: istio/gateway
  #   version: 1.20.0
  #   needs:
  #     - istio-system/istiod
  #   wait: false
  #   set:
  #     - name: labels.istio
  #       value: ingressgateway
  #     - name: labels.app
  #       value: istio-ingressgateway
  #     - name: service.type
  #       value: LoadBalancer

  # - name: kiali
  #   namespace: istio-system
  #   chart: kiali/kiali-server
  #   version: 1.78.0
  #   needs:
  #     - istio-system/istiod
  #   wait: true
  #   values:
  #     - istio/kiali-values.yaml
  #   hooks:
  #     - events: ["presync"]
  #       showlogs: true
  #       command: sh
  #       args:
  #         - "-c"
  #         - |
  #           kubectl delete clusterrole kiali-viewer kiali 2>/dev/null || true
  #           kubectl delete clusterrolebinding kiali-viewer kiali 2>/dev/null || true

  # - name: prometheus
  #   namespace: istio-system
  #   chart: prometheus-community/kube-prometheus-stack
  #   needs:
  #     - istio-system/istiod
  #   values:
  #     - istio/prometheus-values.yaml
  #   wait: true
  #   timeout: 900

  # - name: jaeger
  #   namespace: istio-system
  #   chart: jaegertracing/jaeger
  #   wait: true

  # - name: istio-config
  #   namespace: muffin
  #   createNamespace: true
  #   chart: ./istio-config
  #   values:
  #     - istio-config/values.yaml
  #   needs:
  #     - istio-system/istiod
  #     - istio-system/prometheus
  #   wait: false
  #   hooks:
  #     - events: ["presync"]
  #       showlogs: true
  #       command: sh
  #       args:
  #         - "-c"
  #         - |
  #           kubectl annotate namespace muffin \
  #             meta.helm.sh/release-name=istio-config \
  #             meta.helm.sh/release-namespace=muffin \
  #             --overwrite 2>/dev/null || true
  #           kubectl label namespace muffin \
  #             app.kubernetes.io/managed-by=Helm \
  #             istio-injection=enabled \
  #             sidecar.istio.io/inject=true \
  #             --overwrite 2>/dev/null || true

  - name: muffin-currency
    namespace: muffin
    createNamespace: true
    chart: ./muffin-currency
    needs:
      # - muffin/istio-config
    values:
      - muffin-currency/values.yaml

  - name: muffin-wallet
    namespace: muffin
    createNamespace: false
    chart: ./muffin-wallet
    needs:
      - muffin/muffin-currency
      # - muffin/istio-config
    values:
      - muffin-wallet/values.yaml

