{
 "title": "lobLevel + traceId",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "traceId",
    "label": "traceId",
    "query": {}
   },
   { "name": "logLevel", "label": "logLevel", "query": "INFO, DEBUG, WARN, ERROR" }
  ]
 },
 "panels": [
  {
   "title": "trace",
   "type": "traces",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "query": "${traceId}" }
   ]
  },
  {
   "title": "logLevel",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{logLevel=\"$logLevel\"} |= ``"
    }
   ]
  },
  {
   "title": "logLevel + traceId",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{logLevel=\"$logLevel\", traceId=\"$traceId\"} |= ``"
    }
   ]
  }
 ]
}