{{- if .Values.destinationRules.wallet.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: muffin-wallet
  namespace: muffin
spec:
  host: muffin-wallet
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 10
        http2MaxRequests: 100
        maxRequestsPerConnection: 2
        maxRetries: 3
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
    tls:
      mode: ISTIO_MUTUAL
    portLevelSettings:
    - port:
        number: 8081  # Your metrics port
      tls:
        mode: DISABLE 
{{- end }}
