{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app: istio
    release: prometheus
spec:
  selector:
    matchLabels:
      app: istiod
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
  - port: http-monitoring
    interval: 15s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxy
  namespace: istio-system
  labels:
    app: istio
    release: prometheus
spec:
  selector:
    matchLabels:
      security.istio.io/tlsMode: istio
  namespaceSelector:
    matchNames:
      - istio-system
      - muffin
  podMetricsEndpoints:
  - interval: 15s
    path: /stats/prometheus
    port: http-envoy-prom
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_label_app]
      action: replace
      targetLabel: app
  - interval: 15s
    path: /actuator/prometheus
    port: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_label_app]
      action: replace
      targetLabel: app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: muffin-wallet
  namespace: {{ .Values.namespace.name }}
  labels:
    app: muffin-wallet
    release: prometheus
spec:
  selector:
    matchLabels:
      app: muffin-wallet
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace.name }}
  endpoints:
  - port: http-envoy-prom
    path: /stats/prometheus
    interval: 15s
    scrapeTimeout: 10s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_service_name]
      action: replace
      targetLabel: service_name
  - port: http
    path: /actuator/prometheus
    interval: 15s
    scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: muffin-currency
  namespace: {{ .Values.namespace.name }}
  labels:
    app: muffin-currency
    release: prometheus
spec:
  selector:
    matchLabels:
      app: muffin-currency
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace.name }}
  endpoints:
  - port: http-envoy-prom 
    path: /stats/prometheus
    # path: /actuator/prometheus
    interval: 15s
    scrapeTimeout: 10s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_service_name]
      action: replace
      targetLabel: service_name
{{- end }}
